services:
  mail:
    image: analogic/poste.io
    hostname: ${MAIL_DOMAIN}
    ports:
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995
      - 8000:8000
      - 4433:4433
    environment:
      - HTTPS=OFF
      - HTTP_PORT=8000
      - HTTPS_PORT=4433
      - VIRTUAL_PORT=8000
      - DISABLE_CLAMAV=TRUE
      - DISABLE_RSPAMD=TRUE
      - VIRTUAL_HOST=${MAIL_DOMAIN}
      - LETSENCRYPT_HOST=${MAIL_DOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/mail:/data
      - ${PROXY_DATA}/html/.well-known:/opt/www/.well-known
      - ${PROXY_DATA}/certs/${MAIL_DOMAIN}/cert.pem:/data/ssl/server.crt:ro
      - ${PROXY_DATA}/certs/${MAIL_DOMAIN}/key.pem:/data/ssl/server.key:ro
      - ${PROXY_DATA}/certs/${MAIL_DOMAIN}/chain.pem:/data/ssl/ca.crt:ro

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  api:
    image: arwichok/boris:alpine
    build:
      context: ./api
    expose:
      - 8080
    depends_on:
      - db
      - mail
    deploy:
      restart_policy:
        condition: always
        delay: 10s
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      MAIL_HOSTNAME: ${MAIL_DOMAIN}
      MAIL_USERNAME: noreply@${DOMAIN}
      MAIL_PASSWORD: noreply
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${DOMAIN}

networks:
  default:
    name: proxy
    external: true